hostnamePortList: "localhost:8983"
solrCollection: "test"

# warm-up and run duration
benchmarkWarmupTime: 60
benchmarkMeasurementTime: 900

# resources
maxNumberOfThreads: 100
maxNumberOfClients: 100

# distribute 'resources' proportionately b/w select and update queries
writePercent: 0

# 'requested rate'
# Run the 'select' queries at a very high rate 100K req/sec (throughput mode)
targetRateForSelectOpAtWarmup: 100000
targetRateForSelectOp: 100000

# Override rate 'requested rate' values of update queries
# Run the 'update' queries at a fixed rate instead of the values set via writePercent
targetRateForUpdateOpAtWarmup: 1000
targetRateForUpdateOp: 1000

selectQueryFiles: "QueryFiles/10000/COMMENT_FIELD.txt QueryFiles/10000/TEXT_FIELD.txt QueryFiles/10000/TITLE_FIELD.txt QueryFiles/10000/USERNAME_FIELD.txt"
documentIdFile: "QueryFiles/10000/docIdFile.txt"

recordingLatency: true # (Only interested in throughput scores)
maxUsableSelectQueries: 10000
